"""The LTC bench checkpoint, software half (docs/ltc-plan.md).

Runs the exact bench script in the real shell: the WAV a phone would
play into the line-in is generated by write_ltc_wav and read back from
disk, its samples land in the capture ring buffer, and everything else
is the production path - real MainWindow, the Structure tab's real ARM
CHASE chip, real LTCInputService/decoder/chase/runner, the real
timeline transport. Songs fire at their SMPTE start times, the
playhead follows, a pulled cable freewheels and never stops the show,
the returning signal fires the next song, STOP disarms.

The only piece left for the physical bench is the line-in device
itself (open + decode a real analog signal).
"""

import wave

import numpy as np
import pytest

from config.models import (Setlist, SetlistEntry, ShowPart, Song,
                           SongTrigger, TimelineData)
from utils.timecode import FPS_25, Timecode, write_ltc_wav

SR = 44100
CHUNK = 2205        # 50 ms of samples per drain
DT = 0.05


class FakeAudioInput:
    """A LiveAudioInput whose 'device' is the test pushing samples."""

    def __init__(self, sample_rate=SR, channels=1):
        from audio.ring_buffer import AudioRingBuffer
        self.sample_rate = sample_rate
        self.ring_buffer = AudioRingBuffer(
            max_seconds=30.0, sample_rate=sample_rate, channels=channels)
        self.active = False

    def initialize(self, device_index=None):
        return True

    def start(self):
        self.active = True
        return True

    def stop(self):
        self.active = False

    def cleanup(self):
        self.active = False

    def is_active(self):
        return self.active


class FakeClock:
    def __init__(self, t=5000.0):
        self.t = t

    def __call__(self):
        return self.t


def _song(name):
    # 4 bars of 4/4 at 120 BPM = 8 s.
    return Song(name=name,
                parts=[ShowPart(name="All", color="#00FF00",
                                signature="4/4", bpm=120.0, num_bars=4,
                                transition="instant")],
                effects=[], timeline_data=TimelineData())


def _feed(window, service, clock, samples, start_s, end_s):
    """Play the WAV segment [start_s, end_s) 'into the line-in'."""
    fake = service._audio
    i = int(start_s * SR)
    end = int(end_s * SR)
    while i < end:
        fake.ring_buffer.write(
            np.asarray(samples[i:i + CHUNK]).reshape(-1, 1))
        i += CHUNK
        clock.t += DT
        service.drain_once()
        window._ltc_tick()


@pytest.fixture
def chase_window(main_window, monkeypatch, tmp_path):
    import audio.ltc_input as ltc_input_mod
    monkeypatch.setattr(ltc_input_mod, "LiveAudioInput", FakeAudioInput)

    cfg = main_window.config
    cfg.songs["Eins"] = _song("Eins")
    cfg.songs["Zwei"] = _song("Zwei")
    cfg.setlist = Setlist(name="TC Set", sync_mode="smpte", entries=[
        SetlistEntry(song="Eins", trigger=SongTrigger(
            mode="smpte", timecode="01:00:00:05")),   # 3600.2 .. 3608.2
        SetlistEntry(song="Zwei", trigger=SongTrigger(
            mode="smpte", timecode="01:00:09:00")),   # 3609.0 .. 3617.0
    ])
    main_window.shows_tab.update_from_config()

    clock = FakeClock()
    service = main_window.ltc_service()
    service._clock = clock            # deterministic arrivals

    # The bench artifact itself: written to disk, read back like a
    # soundcard would deliver it.
    wav_path = str(tmp_path / "bench_ltc.wav")
    write_ltc_wav(wav_path, Timecode.parse("01:00:00:00", FPS_25), 12.0)
    with wave.open(wav_path, "rb") as w:
        pcm = np.frombuffer(w.readframes(w.getnframes()), dtype="<i2")
    samples = pcm.astype(np.float64) / 32767.0

    return main_window, service, clock, samples


class TestLtcChaseEndToEnd:

    def test_the_bench_script_in_software(self, chase_window):
        window, service, clock, samples = chase_window
        shows = window.shows_tab
        structure = window.structure_tab
        chip = window.live_tab._sync_chip

        # ARM via the real Structure-tab chip.
        structure._refresh_sync_chase_row()
        assert structure.chase_arm_btn.isEnabled()
        structure.chase_arm_btn.setChecked(True)
        assert window.ltc_chase_armed()
        assert structure.chase_arm_btn.text() == "CHASING"
        assert not shows.play_btn.isEnabled()
        assert chip.text() == "SYNC LTC · NO SIG"

        # Timecode rolls from 01:00:00:00; song 1 fires at frame :05
        # and the playhead chases.
        _feed(window, service, clock, samples, 0.0, 2.0)
        assert chip.text() == "SYNC LTC"
        assert shows.is_playing
        assert shows.show_combo.currentData() == "Eins"
        t = service.position()
        expected = t - Timecode.parse("01:00:00:05", FPS_25).to_seconds()
        assert shows._get_current_position() == \
            pytest.approx(expected, abs=0.13)

        # Cable pulled: freewheel, the show keeps running.
        clock.t += 1.0
        service.drain_once()
        window._ltc_tick()
        assert chip.text() == "SYNC LTC · FW"
        assert shows.is_playing

        # Deep silence, freewheel expired: STILL running - a dropped
        # cable must never black out a gig.
        clock.t += 8.0
        service.drain_once()
        window._ltc_tick()
        assert chip.text() == "SYNC LTC · NO SIG"
        assert shows.is_playing
        assert shows.show_combo.currentData() == "Eins"

        # Replugged: the desk kept rolling meanwhile, so the signal
        # returns inside song 2's window - it fires and re-locks.
        _feed(window, service, clock, samples, 9.0, 11.0)
        assert chip.text() == "SYNC LTC"
        assert shows.is_playing
        assert shows.show_combo.currentData() == "Zwei"
        t = service.position()
        expected = t - Timecode.parse("01:00:09:00", FPS_25).to_seconds()
        assert shows._get_current_position() == \
            pytest.approx(expected, abs=0.13)

        # The operator's STOP: disarm, back to manual, chip internal.
        shows._on_stop_clicked()
        assert not window.ltc_chase_armed()
        assert not shows.is_playing
        assert shows.play_btn.isEnabled()
        assert structure.chase_arm_btn.text() == "ARM CHASE"
        assert chip.text() == "SYNC INT"
        assert not service.is_running
