# utils/export_cli.py
"""Headless .qxw export - the ``export`` subcommand of the app entry.

``python main.py export config.yaml --out workspace.qxw --qlc-version
5.2.1`` loads a project config and writes the QLC+ workspace without
starting Qt, for batch workflows (export N variants for N venues) and
scripted setups. main.py dispatches here BEFORE any PyQt import, so
the command runs on machines with no display; everything Qt-free the
GUI export path uses (Configuration.load, create_qlc_workspace) is
shared, not duplicated.

Notes:
- The Virtual Console is generated by default with the same full
  option set as the GUI dialog's defaults; ``--no-vc`` skips it.
- The packaged Windows app is a windowed exe (lichtmaschine.spec,
  console=False): running its ``export`` subcommand works but prints
  nothing to a console. From source, output behaves normally.
"""

import argparse
import os
import sys

# The QLC+ target versions the Workspace Options dialog offers. The
# workspace XML schema is identical between them; the value only stamps
# <Creator><Version>.
QLC_VERSIONS = ("4.14.4", "5.2.1")

# Mirrors the GUI dialog's default checkbox state (everything on,
# light background) so headless and interactive exports match.
DEFAULT_VC_OPTIONS = {
    "generate_vc": True,
    "group_controls": True,
    "scene_presets": True,
    "movement_presets": True,
    "show_buttons": True,
    "speed_dial": True,
    "master_presets": True,
    "dark_mode": False,
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="lichtmaschine export",
        description="Export a project config to a QLC+ .qxw workspace "
                    "without starting the app.",
        epilog="Example: lichtmaschine export show.yaml "
               "--out venue_a.qxw --qlc-version 5.2.1",
    )
    parser.add_argument(
        "config",
        help="the project config YAML to export")
    parser.add_argument(
        "--out", "-o", metavar="FILE.qxw",
        help="output workspace path (default: the config's name with "
             ".qxw, next to the config)")
    parser.add_argument(
        "--qlc-version", choices=QLC_VERSIONS, default=QLC_VERSIONS[0],
        help="QLC+ version stamped into <Creator><Version> (cosmetic; "
             "the schema is identical - default %(default)s)")
    parser.add_argument(
        "--no-vc", action="store_true",
        help="skip Virtual Console generation (functions and patch only)")
    parser.add_argument(
        "--dark-mode", action="store_true",
        help="dark Virtual Console background")
    return parser


def default_output_path(config_path: str) -> str:
    """<config dir>/<config stem>.qxw - a CLI wants its output next to
    its input, not the historical workspace.qxw in the app root."""
    base, _ = os.path.splitext(os.path.abspath(config_path))
    return base + ".qxw"


def run_export_cli(argv) -> int:
    """The ``export`` subcommand. Returns a process exit code (0 ok,
    1 export failure, 2 usage via argparse's own exit)."""
    args = build_parser().parse_args(argv)

    config_path = args.config
    if not os.path.isfile(config_path):
        print(f"error: config not found: {config_path}", file=sys.stderr)
        return 1

    out_path = args.out or default_output_path(config_path)
    out_dir = os.path.dirname(os.path.abspath(out_path))
    if not os.path.isdir(out_dir):
        print(f"error: output directory not found: {out_dir}",
              file=sys.stderr)
        return 1

    # Deferred so `--help` and argument errors stay instant.
    from config.models import Configuration
    from utils.create_workspace import create_qlc_workspace

    try:
        config = Configuration.load(config_path)
    except Exception as exc:
        print(f"error: could not load {config_path}: {exc}",
              file=sys.stderr)
        return 1

    vc_options = dict(DEFAULT_VC_OPTIONS)
    vc_options["qlc_target_version"] = args.qlc_version
    if args.no_vc:
        vc_options["generate_vc"] = False
    if args.dark_mode:
        vc_options["dark_mode"] = True

    try:
        create_qlc_workspace(config, vc_options, output_path=out_path)
    except Exception as exc:
        print(f"error: export failed: {exc}", file=sys.stderr)
        return 1

    print(f"Workspace written to {out_path}")
    return 0
